<a href="https://colab.research.google.com/github/Vineeth37/ML/blob/main/Adaboost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = sns.load_dataset('iris')
df['species'] = df['species'].map({'setosa':0,'versicolor':1,'virginica':2}).astype(int)
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
X = df.iloc[: , :-1]
y = df.iloc[: , -1]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
len(X_train),len(y_train)

(120, 120)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
values = [3,5,7,9,11]
for i in values:
  reg = AdaBoostClassifier(estimator=lr,n_estimators=i)
  reg.fit(X_train,y_train)
  print(f'Number of LR are : {i} and Train accuracy was : {reg.score(X_train,y_train)}')
  print(f'Number of LR are : {i} and Test accuracy was : {reg.score(X_test,y_test)}')
  print(f'when LR : {i} -> confusion Matrix was : {confusion_matrix(y_test,reg.predict(X_test))}')
  print('---------------------------------------------------')

Number of LR are : 3 and Train accuracy was : 0.875
Number of LR are : 3 and Test accuracy was : 0.9666666666666667
when LR : 3 -> confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  1 10]]
---------------------------------------------------
Number of LR are : 5 and Train accuracy was : 0.8666666666666667
Number of LR are : 5 and Test accuracy was : 0.9333333333333333
when LR : 5 -> confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  2  9]]
---------------------------------------------------
Number of LR are : 7 and Train accuracy was : 0.8666666666666667
Number of LR are : 7 and Test accuracy was : 0.9333333333333333
when LR : 7 -> confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  2  9]]
---------------------------------------------------
Number of LR are : 9 and Train accuracy was : 0.8666666666666667
Number of LR are : 9 and Test accuracy was : 0.9333333333333333
when LR : 9 -> confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  2  9]]
-----------------------------------------

**Gradient_Boosting**

In [ ]:
lr_values = np.random.rand(10,10)
lr_values = lr_values.ravel()
lr_values

array([0.42712915, 0.25442465, 0.74579196, 0.41487507, 0.6756821 ,
       0.49856702, 0.31128976, 0.9125335 , 0.23111978, 0.72887263,
       0.35219189, 0.68077405, 0.13502381, 0.82282299, 0.98287731,
       0.82207701, 0.06171812, 0.30389821, 0.09309554, 0.5057037 ,
       0.44310307, 0.81533153, 0.67468828, 0.74096341, 0.6254501 ,
       0.12141799, 0.73988127, 0.69496154, 0.26521478, 0.45682146,
       0.97447766, 0.38769199, 0.85967603, 0.2441965 , 0.59065289,
       0.81617657, 0.08235966, 0.09943967, 0.39673358, 0.75820714,
       0.67912577, 0.78410157, 0.05178301, 0.68151578, 0.55857986,
       0.64704554, 0.40693522, 0.18627895, 0.08694303, 0.71429278,
       0.88480262, 0.78292124, 0.78225332, 0.17476405, 0.62051921,
       0.82914234, 0.94745544, 0.54116985, 0.62332968, 0.44057711,
       0.00919741, 0.71553362, 0.21511211, 0.05142506, 0.00990184,
       0.2675584 , 0.48190888, 0.63571612, 0.38620312, 0.99237526,
       0.79402243, 0.92050614, 0.47312378, 0.41666563, 0.28304

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
lr_values = np.random.rand(10,10)
lr_values = lr_values.ravel()
for i in lr_values:
  gb = GradientBoostingClassifier(n_estimators=11,learning_rate=i)
  gb.fit(X_train,y_train)
  print(f'learning Rate value : {i} and Train accuracy was : {gb.score(X_train,y_train)}')
  print(f'learning Rate value : {i} and Test accuracy was : {gb.score(X_test,y_test)}')
  print(f'learning Rate value: {i} -> confusion Matrix was : {confusion_matrix(y_test,gb.predict(X_test))}')

learning Rate value : 0.8051964822030986 and Train accuracy was : 1.0
learning Rate value : 0.8051964822030986 and Test accuracy was : 1.0
learning Rate value: 0.8051964822030986 -> confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
learning Rate value : 0.5666167501242982 and Train accuracy was : 1.0
learning Rate value : 0.5666167501242982 and Test accuracy was : 1.0
learning Rate value: 0.5666167501242982 -> confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
learning Rate value : 0.17262299467803455 and Train accuracy was : 1.0
learning Rate value : 0.17262299467803455 and Test accuracy was : 1.0
learning Rate value: 0.17262299467803455 -> confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
learning Rate value : 0.23115270028739565 and Train accuracy was : 1.0
learning Rate value : 0.23115270028739565 and Test accuracy was : 1.0
learning Rate value: 0.23115270028739565 -> confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
learning Rate value : 0.46

**Xtreme_Gradient_Boosting**

In [ ]:
import xgboost
from xgboost import XGBClassifier

lr_values = np.random.rand(10,10)
lr_values = lr_values.ravel()
for i in lr_values:
  xg = XGBClassifier(n_estimators=11,learning_rate=i)
  xg.fit(X_train,y_train)
  print(f'learning Rate value : {i} and Train accuracy was : {xg.score(X_train,y_train)}')
  print(f'learning Rate value : {i} and Test accuracy was : {xg.score(X_test,y_test)}')
  print(f'learning Rate value: {i} -> confusion Matrix was : {confusion_matrix(y_test,xg.predict(X_test))}')

learning Rate value : 0.23944845891573108 and Train accuracy was : 0.9833333333333333
learning Rate value : 0.23944845891573108 and Test accuracy was : 1.0
learning Rate value: 0.23944845891573108 -> confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
learning Rate value : 0.7573917997700986 and Train accuracy was : 1.0
learning Rate value : 0.7573917997700986 and Test accuracy was : 1.0
learning Rate value: 0.7573917997700986 -> confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
learning Rate value : 0.05982964218754905 and Train accuracy was : 0.975
learning Rate value : 0.05982964218754905 and Test accuracy was : 1.0
learning Rate value: 0.05982964218754905 -> confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
learning Rate value : 0.6472956800642757 and Train accuracy was : 1.0
learning Rate value : 0.6472956800642757 and Test accuracy was : 1.0
learning Rate value: 0.6472956800642757 -> confusion Matrix was : [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
learning 

**SVM**

In [ ]:
from sklearn.svm import SVC
reg_svm = SVC(kernel='rbf')

In [ ]:
reg_svm.fit(X_train,y_train)

SVC()

In [ ]:
print(f'Train Accuracy : {reg_svm.score(X_train,y_train)}')

Train Accuracy : 0.975


In [ ]:
print(f'Test Accuracy : {reg_svm.score(X_test,y_test)}')

Test Accuracy : 1.0


**cross_validation**

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn_reg = KNeighborsClassifier()

In [ ]:
X.shape

(150, 4)

In [ ]:
accs = cross_val_score(knn_reg,X,y,cv=15)
print(accs)
print(sum(accs) / 15.0)

[1.  1.  0.9 1.  1.  1.  0.8 1.  1.  0.9 1.  1.  1.  1.  1. ]
0.9733333333333333
