<a href="https://colab.research.google.com/github/Vineeth37/ML/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [ ]:
df = pd.read_csv('/content/50_Startups.csv')
df.head(7)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51

In [ ]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [ ]:
len(df)

50

In [ ]:
df.shape

(50, 5)

In [ ]:
df.size

250

In [ ]:
df['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [ ]:
df['State'].value_counts()

State
New York      17
California    17
Florida       16
Name: count, dtype: int64

In [ ]:
df['State'] = df['State'].map({'New York':0,'California':1,'Florida':2}).astype(int)

In [ ]:
df.head(7)

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      0  192261.83
1  162597.70       151377.59        443898.53      1  191792.06
2  153441.51       101145.55        407934.54      2  191050.39
3  144372.41       118671.85        383199.62      0  182901.99
4  142107.34        91391.77        366168.42      2  166187.94
5  131876.90        99814.71        362861.36      0  156991.12
6  134615.46       147198.87        127716.82      1  156122.51

In [ ]:
df['State'].value_counts()

State
0    17
1    17
2    16
Name: count, dtype: int64

In [ ]:
X = df.iloc[: , :-1] # independent
y = df.iloc[: , -1] # dependent

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
len(X_train) , len(y_train)

(40, 40)

In [ ]:
len(X_test),len(y_test)

(10, 10)

In [ ]:
# algorithm

from sklearn.linear_model import LinearRegression

reg = LinearRegression()


reg.fit(X_train,y_train)

LinearRegression()

In [ ]:
# y = m1x1 + m2x2 + m3x3 + m4x4 + c


In [ ]:
reg.coef_

array([ 8.05374582e-01, -6.83047865e-02,  3.04739678e-02,  4.65048387e+02])

In [ ]:
reg.intercept_

53697.72230692505

In [ ]:
# y = m1x1 + m2x2 + m3x3 + m4x4 + c

# model = 8.05374582e-01*x1 + -6.83047865e-02*x2+ 3.04739678e-02*x3+ 4.65048387e+02*x4 + 53697.72230692505

**train_Performance**

In [ ]:
8.05374582e-01*93863.75	 + -6.83047865e-02*127320.38+ 3.04739678e-02*249839.44+ 4.65048387e+02*2 + 53697.72230692505

129140.30517885872

In [ ]:
reg.coef_[0] * 93863.75 + reg.coef_[1] * 127320.38 + reg.coef_[2] *  249839.44	 + reg.coef_[3] * 2 + reg.intercept_

129140.3052040884

In [ ]:
y_train_predictions = reg.predict(X_train)

In [ ]:
y_train_predictions

array([129140.30520409, 173993.5679776 ,  92156.97253522, 150117.48123615,
       173543.34920814, 156416.29143989,  76317.99193059,  56830.71210391,
        44912.46383215, 145534.17020003, 155364.24071987, 116742.52519807,
       113249.49118107,  87205.73929018,  95193.49626801, 191892.1236586 ,
        62313.62978213, 113800.50179366,  98822.69031417, 164148.02850256,
        99346.81771325, 136582.37778368,  75163.46774832, 188302.3609556 ,
       115461.33217633, 183728.36994208,  58567.68947208,  91210.03515154,
       111081.01315238,  74489.28424779, 136135.35965573, 115077.8487642 ,
       129708.87700834,  47548.81958104, 116899.50116014, 159496.02894197,
        71142.54373166, 148351.08425857,  98948.91286934,  71131.32330986])

In [ ]:
X_train

R&D Spend  Administration  Marketing Spend  State
12   93863.75       127320.38        249839.44      2
4   142107.34        91391.77        366168.42      2
37   44069.95        51283.14        197029.42      1
8   120542.52       148718.95        311613.29      0
3   144372.41       118671.85        383199.62      0
6   134615.46       147198.87        127716.82      1
41   27892.92        84710.77        164470.71      2
46    1315.46       115816.21        297114.46      2
47       0.00       135426.92             0.00      1
15  114523.61       122616.84        261776.23      0
9   123334.88       108679.17        304981.62      1
16   78013.11       121597.55        264346.06      1
24   77044.01        99281.34        140574.81      0
34   46426.07       157693.92        210797.67      1
31   61136.38       152701.92         88218.23      0
0   165349.20       136897.80        471784.10      0
44   22177.74       154806.14         28334.72      1
27   72107.60       127864.55        353183.81      0
33   55493.95       103057.49        214634.81      2
5   131876.90        99814.71        362861.36      0
29   65605.48       153032.06        107138.38      0
11  100671.96        91790.61        249744.55      1
36   28663.76       127056.21        201126.82      2
1   162597.70       151377.59        443898.53      1
21   78389.47       153773.43        299737.29      0
2   153441.51       101145.55        407934.54      2
43   15505.73       127382.30         35534.17      0
35   46014.02        85047.44        205517.64      0
23   67532.53       105751.03        304768.73      2
40   28754.33       118546.05        172795.67      1
10  101913.08       110594.11        229160.95      2
22   73994.56       122782.75        303319.26      2
18   91749.16       114175.79        294919.57      2
49       0.00       116983.80         45173.06      1
20   76253.86       113867.30        298664.47      1
7   130298.13       145530.06        323876.68      2
42   23640.93        96189.63        148001.11      1
14  119943.24       156547.42        256512.92      2
28   66051.52       182645.56        118148.20      2
38   20229.59        65947.93        185265.10      0

In [ ]:
Training_data_Performance = pd.DataFrame()
Training_data_Performance = X_train.copy()
Training_data_Performance['Actual_y_train'] = y_train.copy()
Training_data_Performance['y_train_pred'] = y_train_predictions


Training_data_Performance

R&D Spend  Administration  Marketing Spend  State  Actual_y_train  \
12   93863.75       127320.38        249839.44      2       141585.52   
4   142107.34        91391.77        366168.42      2       166187.94   
37   44069.95        51283.14        197029.42      1        89949.14   
8   120542.52       148718.95        311613.29      0       152211.77   
3   144372.41       118671.85        383199.62      0       182901.99   
6   134615.46       147198.87        127716.82      1       156122.51   
41   27892.92        84710.77        164470.71      2        77798.83   
46    1315.46       115816.21        297114.46      2        49490.75   
47       0.00       135426.92             0.00      1        42559.73   
15  114523.61       122616.84        261776.23      0       129917.04   
9   123334.88       108679.17        304981.62      1       149759.96   
16   78013.11       121597.55        264346.06      1       126992.93   
24   77044.01        99281.34        140574.81      0       108552.04   
34   46426.07       157693.92        210797.67      1        96712.80   
31   61136.38       152701.92         88218.23      0        97483.56   
0   165349.20       136897.80        471784.10      0       192261.83   
44   22177.74       154806.14         28334.72      1        65200.33   
27   72107.60       127864.55        353183.81      0       105008.31   
33   55493.95       103057.49        214634.81      2        96778.92   
5   131876.90        99814.71        362861.36      0       156991.12   
29   65605.48       153032.06        107138.38      0       101004.64   
11  100671.96        91790.61        249744.55      1       144259.40   
36   28663.76       127056.21        201126.82      2        90708.19   
1   162597.70       151377.59        443898.53      1       191792.06   
21   78389.47       153773.43        299737.29      0       111313.02   
2   153441.51       101145.55        407934.54      2       191050.39   
43   15505.73       127382.30         35534.17      0        69758.98   
35   46014.02        85047.44        205517.64      0        96479.51   
23   67532.53       105751.03        304768.73      2       108733.99   
40   28754.33       118546.05        172795.67      1        78239.91   
10  101913.08       110594.11        229160.95      2       146121.95   
22   73994.56       122782.75        303319.26      2       110352.25   
18   91749.16       114175.79        294919.57      2       124266.90   
49       0.00       116983.80         45173.06      1        14681.40   
20   76253.86       113867.30        298664.47      1       118474.03   
7   130298.13       145530.06        323876.68      2       155752.60   
42   23640.93        96189.63        148001.11      1        71498.49   
14  119943.24       156547.42        256512.92      2       132602.65   
28   66051.52       182645.56        118148.20      2       103282.38   
38   20229.59        65947.93        185265.10      0        81229.06   

     y_train_pred  
12  129140.305204  
4   173993.567978  
37   92156.972535  
8   150117.481236  
3   173543.349208  
6   156416.291440  
41   76317.991931  
46   56830.712104  
47   44912.463832  
15  145534.170200  
9   155364.240720  
16  116742.525198  
24  113249.491181  
34   87205.739290  
31   95193.496268  
0   191892.123659  
44   62313.629782  
27  113800.501794  
33   98822.690314  
5   164148.028503  
29   99346.817713  
11  136582.377784  
36   75163.467748  
1   188302.360956  
21  115461.332176  
2   183728.369942  
43   58567.689472  
35   91210.035152  
23  111081.013152  
40   74489.284248  
10  136135.359656  
22  115077.848764  
18  129708.877008  
49   47548.819581  
20  116899.501160  
7   159496.028942  
42   71142.543732  
14  148351.084259  
28   98948.912869  
38   71131.323310

In [ ]:
Training_data_Performance.index

Index([12,  4, 37,  8,  3,  6, 41, 46, 47, 15,  9, 16, 24, 34, 31,  0, 44, 27,
       33,  5, 29, 11, 36,  1, 21,  2, 43, 35, 23, 40, 10, 22, 18, 49, 20,  7,
       42, 14, 28, 38],
      dtype='int64')

In [ ]:
count = 0
for i in Training_data_Performance.index:
  count = count + (Training_data_Performance['Actual_y_train'][i] - Training_data_Performance['y_train_pred'][i])**2

print(count / len(Training_data_Performance))

79745387.33818817


In [ ]:
from sklearn.metrics import mean_squared_error,r2_score

In [ ]:
mean_squared_error(y_train,y_train_predictions)

79745387.33818817

In [ ]:
r2_score(y_train,y_train_predictions)

0.9536756687881015

In [ ]:
reg.score(X_train,y_train)

0.9536756687881015

In [ ]:
# test Performance

In [ ]:
y_test_pred = reg.predict(X_test)
y_test_pred

array([126695.84447449,  84881.66366689,  99434.87504764,  46081.05553217,
       128633.86029563,  50599.97078397, 109535.63646669, 100914.2041375 ,
        97808.73738339, 112812.20359319])

In [ ]:
r2_score(y_test,y_test_pred)

0.8990092409390612

In [ ]:
# new data point

In [ ]:
X_train.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State'], dtype='object')

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
reg.coef_[0] * 56000 + reg.coef_[1] * 13000 + reg.coef_[2] *  45000	 + reg.coef_[3] * 1 + reg.intercept_

99747.1136333461

In [ ]:
reg.predict([[56000,13000,45000,1]])

array([99747.11363335])

In [ ]:
import numpy

In [ ]:
numpy.__version__

'1.26.4'

In [ ]:
'''
In this file we are going to develop and Multiple Linear Regression with Oops concept
'''
import numpy as np
import pandas as pd
import sklearn
import sys
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
class TRAINING:
    def __init__(self,location):
        try:
            self.df = pd.read_csv(location)
            self.df['State'] = self.df['State'].map({'New York':0,'California':1,'Florida':2}).astype(int)
            self.X = self.df.iloc[: , :-1] # independent
            self.y = self.df.iloc[: , -1] # dependent
            self.X_train,self.X_test,self.y_train,self.y_test = train_test_split(self.X,self.y,test_size=0.2,random_state=42)
        except Exception as e:
            error_type, error_msg, err_line = sys.exc_info()
            print(f'Error from Line {err_line.tblineno} -> type {error_type} -> Error msg -> {error_msg}')
    def data_training(self):
        try:
            self.reg = LinearRegression()
            self.reg.fit(self.X_train,self.y_train) # trainnig
        except Exception as e:
            error_type, error_msg, err_line = sys.exc_info()
            print(f'Error from Line {err_line.tblineno} -> type {error_type} -> Error msg -> {error_msg}')
    def train_performance(self):
        try:
            self.y_train_pred = self.reg.predict(self.X_train)
            print(f' Train Accuracy : -> {r2_score(self.y_train,self.y_train_pred)}')
            print(f'Train Loss : {mean_squared_error(self.y_train,self.y_train_pred)}')
        except Exception as e:
            error_type, error_msg, err_line = sys.exc_info()
            print(f'Error from Line {err_line.tblineno} -> type {error_type} -> Error msg -> {error_msg}')
    def testing(self):
        try:
            self.y_test_pred = self.reg.predict(self.X_test)
            print(f' Test Accuracy : -> {r2_score(self.y_test, self.y_test_pred)}')
        except Exception as e:
            error_type, error_msg, err_line = sys.exc_info()
            print(f'Error from Line {err_line.tblineno} -> type {error_type} -> Error msg -> {error_msg}')

if __name__ == "__main__":
    try:
        obj = TRAINING('50_Startups.csv') # constructor will be called
        obj.data_training()
        obj.train_performance()
        obj.testing()
    except Exception as e:
        error_type,error_msg,err_line = sys.exc_info()
        print(f'Error from Line {err_line.tblineno} -> type {error_type} -> Error msg -> {error_msg}')

 Train Accuracy : -> 0.9536756687881015
Train Loss : 79745387.33818817
 Test Accuracy : -> 0.8990092409390612


In [ ]:
# overfitting Problem -> Training Performance will be good [95%] and Testing Performance will be not so good [45%]
# underfitting Problem -> Training Performance will be not good [45%] and Testing Performance will be not so good [25%]