<a href="https://colab.research.google.com/github/Vineeth37/ML/blob/main/Naive_Bayes_class_room.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns

In [ ]:
from sklearn import datasets


In [ ]:
df = datasets.load_breast_cancer()
dir(df)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [ ]:
df['data']

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
data_loading = pd.DataFrame(data=df['data'] , columns=df['feature_names'])
data_loading['dep'] = df['target']
data_loading

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  dep  
0                  0.2654          0.4601                  0.11890    0  
1                  0.1860          0.2750                  0.08902    0  
2                  0.2430          0.3613                  0.08758    0  
3                  0.2575          0.6638                  0.17300    0  
4                  0.1625          0.2364                  0.07678    0  
..   

In [ ]:
data_loading['dep'].unique()

array([0, 1])

In [ ]:
df = data_loading.copy()
df.shape

(569, 31)

In [ ]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
dep                        0
dtype: int64

In [ ]:
# split

X = df.iloc[: , :-1]
y = df.iloc[: , -1]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
len(X_train),len(y_train)

(455, 455)

In [ ]:
len(X_test),len(y_test)

(114, 114)

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
reg_nb = GaussianNB()

reg_nb.fit(X_train,y_train)

GaussianNB()

In [ ]:
# train_performance

y_train_pred = reg_nb.predict(X_train)

from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(f'Confusion Matrix : {confusion_matrix(y_train,y_train_pred)}')

print(f'Accuracy_score : {accuracy_score(y_train,y_train_pred)}')

print(classification_report(y_train,y_train_pred))

Confusion Matrix : [[149  20]
 [  9 277]]
Accuracy_score : 0.9362637362637363
              precision    recall  f1-score   support

           0       0.94      0.88      0.91       169
           1       0.93      0.97      0.95       286

    accuracy                           0.94       455
   macro avg       0.94      0.93      0.93       455
weighted avg       0.94      0.94      0.94       455



In [ ]:
# train_performance

y_test_pred = reg_nb.predict(X_test)

from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(f'Confusion Matrix : {confusion_matrix(y_test,y_test_pred)}')

print(f'Accuracy_score : {accuracy_score(y_test,y_test_pred)}')

print(classification_report(y_test,y_test_pred))

Confusion Matrix : [[40  3]
 [ 0 71]]
Accuracy_score : 0.9736842105263158
              precision    recall  f1-score   support

           0       1.00      0.93      0.96        43
           1       0.96      1.00      0.98        71

    accuracy                           0.97       114
   macro avg       0.98      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



In [ ]:
X_train.shape

(455, 30)

In [ ]:
f = np.random.rand(5,6).ravel()
f

array([0.47151435, 0.52321721, 0.57727281, 0.32259405, 0.42962587,
       0.4201354 , 0.00793767, 0.25479759, 0.9366163 , 0.53004103,
       0.0332031 , 0.0512689 , 0.17257649, 0.03480587, 0.1627172 ,
       0.51693052, 0.67465497, 0.97052276, 0.37864887, 0.71467629,
       0.56987876, 0.93190326, 0.80910821, 0.1392182 , 0.17126596,
       0.73347421, 0.14683483, 0.99877172, 0.54564659, 0.57459975])

In [ ]:
reg_nb.predict([f])

array([0])

**Logistic_regression**

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
reg_lr = LogisticRegression()

reg_lr.fit(X_train,y_train)

LogisticRegression()

In [ ]:
# train_performance

y_train_pred = reg_lr.predict(X_train)

from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(f'Confusion Matrix : {confusion_matrix(y_train,y_train_pred)}')

print(f'Accuracy_score : {accuracy_score(y_train,y_train_pred)}')

print(classification_report(y_train,y_train_pred))

Confusion Matrix : [[154  15]
 [  9 277]]
Accuracy_score : 0.9472527472527472
              precision    recall  f1-score   support

           0       0.94      0.91      0.93       169
           1       0.95      0.97      0.96       286

    accuracy                           0.95       455
   macro avg       0.95      0.94      0.94       455
weighted avg       0.95      0.95      0.95       455



In [ ]:
# train_performance

y_test_pred = reg_lr.predict(X_test)

from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(f'Confusion Matrix : {confusion_matrix(y_test,y_test_pred)}')

print(f'Accuracy_score : {accuracy_score(y_test,y_test_pred)}')

print(classification_report(y_test,y_test_pred))

Confusion Matrix : [[40  3]
 [ 1 70]]
Accuracy_score : 0.9649122807017544
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        43
           1       0.96      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114



In [ ]:
X_train.shape

(455, 30)

In [ ]:
f = np.random.rand(5,6).ravel()
f

array([0.66044223, 0.69418596, 0.39313705, 0.45841317, 0.5356195 ,
       0.21321696, 0.16648722, 0.09899562, 0.31485408, 0.78617681,
       0.99143631, 0.87316414, 0.29723611, 0.01488163, 0.71160133,
       0.907542  , 0.92537919, 0.3491144 , 0.56087176, 0.71871535,
       0.56130302, 0.31266861, 0.63224226, 0.32139458, 0.51345611,
       0.90151704, 0.61046167, 0.28499096, 0.60199032, 0.57238353])

In [ ]:
reg_lr.predict([f])

array([1])

**Decision_Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
reg_dt = DecisionTreeClassifier(criterion='entropy')

In [ ]:
reg_dt.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [ ]:
# train_performance

y_train_pred = reg_dt.predict(X_train)

from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(f'Confusion Matrix : {confusion_matrix(y_train,y_train_pred)}')

print(f'Accuracy_score : {accuracy_score(y_train,y_train_pred)}')

print(classification_report(y_train,y_train_pred))

Confusion Matrix : [[169   0]
 [  0 286]]
Accuracy_score : 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       169
           1       1.00      1.00      1.00       286

    accuracy                           1.00       455
   macro avg       1.00      1.00      1.00       455
weighted avg       1.00      1.00      1.00       455



In [ ]:
# test_performance

y_test_pred = reg_dt.predict(X_test)

from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(f'Confusion Matrix : {confusion_matrix(y_test,y_test_pred)}')

print(f'Accuracy_score : {accuracy_score(y_test,y_test_pred)}')

print(classification_report(y_test,y_test_pred))

Confusion Matrix : [[39  4]
 [ 1 70]]
Accuracy_score : 0.956140350877193
              precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [ ]:
f = np.random.rand(5,6).ravel()
f

array([0.80855574, 0.85384562, 0.34207204, 0.17293128, 0.52844366,
       0.2851065 , 0.20728315, 0.67625685, 0.76146979, 0.11158526,
       0.17536381, 0.03075162, 0.2169806 , 0.05715063, 0.64205003,
       0.46798764, 0.73166816, 0.6403208 , 0.37260699, 0.38684525,
       0.52360636, 0.25889813, 0.82277866, 0.92688485, 0.68731803,
       0.52007921, 0.82768629, 0.87056689, 0.13222392, 0.46778375])

In [ ]:
reg_dt.predict([f])

array([0])